# Generated by Django 4.1.6 on 2023-02-21 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0011_alter_cart_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='phone',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='seller',
            name='zip_code',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
