# Generated by Django 4.1.6 on 2023-02-21 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0012_alter_seller_phone_alter_seller_zip_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='address',
            new_name='shipping_address',
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('C', 'Confirmed'), ('S', 'Shipped'), ('D', 'Delivered'), ('X', 'Cancelled')], default='P', max_length=1),
        ),
    ]
