# Generated by Django 4.1.6 on 2023-03-01 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0023_alter_review_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='orders', through='ecomapp.OrderProduct', to='ecomapp.product'),
        ),
    ]
