# Generated by Django 4.1.6 on 2023-03-01 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0025_alter_product_brand_alter_product_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='more_images',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='product',
            name='video',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
