# Generated by Django 4.1.6 on 2023-03-02 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0027_alter_product_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_country',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_state',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_zip_code',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
