# Generated by Django 4.1.6 on 2023-03-02 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0030_order_customer_new_alter_paymentmethod_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='order',
            name='customer_new',
        ),
    ]
