# Generated by Django 4.1.6 on 2023-03-02 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0031_remove_order_customer_remove_order_customer_new'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(blank=True, default=5, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='ecomapp.customer'),
            preserve_default=False,
        ),
    ]
