# Generated by Django 4.1.6 on 2023-03-02 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0032_order_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='attachments')),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='more_images',
        ),
        migrations.AddField(
            model_name='product',
            name='more_images',
            field=models.ManyToManyField(blank=True, related_name='products', to='ecomapp.attachment'),
        ),
    ]
