# Generated by Django 4.1.6 on 2023-03-03 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0033_attachment_remove_product_more_images_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmethod',
            name='name',
            field=models.CharField(blank=True, choices=[('Credit', 'Credit Card'), ('Paypal', 'Paypal Account'), ('Apple Pay', 'Apple Pay Account')], default='Credit', max_length=100),
        ),
    ]
