# Generated by Django 4.1.6 on 2023-03-09 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0037_reviewreply'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
